//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""ac422bd1-c0f1-40a3-8ac0-03a9907c8860"",
            ""actions"": [
                {
                    ""name"": ""hit1"",
                    ""type"": ""Button"",
                    ""id"": ""e47c6825-541a-4b26-ad3c-8437e4c5af89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit2"",
                    ""type"": ""Button"",
                    ""id"": ""cbd85d97-5808-4dca-9106-796aaeedfa57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit3"",
                    ""type"": ""Button"",
                    ""id"": ""295e22f8-2d48-4322-afc2-598e8b5fec67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit4"",
                    ""type"": ""Button"",
                    ""id"": ""88251dab-f1ea-467b-beed-1c7e39fa39f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit5"",
                    ""type"": ""Button"",
                    ""id"": ""4281cc3e-e78b-4a89-9a62-e67fae2e48f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit6"",
                    ""type"": ""Button"",
                    ""id"": ""9ce094d4-cf40-462d-878a-82e481a69bfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit7"",
                    ""type"": ""Button"",
                    ""id"": ""9e1962fa-3a64-4ad1-a505-7afe8939d98b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit8"",
                    ""type"": ""Button"",
                    ""id"": ""326ecea7-bd8a-44ac-b836-29cb9858654f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hit9"",
                    ""type"": ""Button"",
                    ""id"": ""c135351c-511e-4174-a640-67e4b5c589ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pause"",
                    ""type"": ""Button"",
                    ""id"": ""23a3bbc7-f1c2-4408-9660-254ce1cdf9f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fa319fd3-1291-4077-be12-b00fc20a5286"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7b3ae7d-c810-4958-a5e1-0201cdbf4158"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a62e791-3079-45f8-9fd7-b0847d5801de"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57b4df7b-c4b4-47d2-8c7a-f588a0316ea1"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e79ed04-3c13-4f07-8780-54869eacabc4"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2b82b98-f10e-48a8-ab1c-03ef89fbd416"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0238a2a-4510-465e-9cbe-ceb1913a1c08"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87544deb-0231-4bde-a8d7-3524481e64ca"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9df00a5c-f1c7-41b2-bfb5-63857161f575"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""837aa284-49d1-4f35-857c-667f5fe0da4e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcf52deb-55ea-44a5-953a-e63f23bcf4e0"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7ac9e27-e754-4a4c-8cd3-7088a687a65d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe4127e7-7345-4b65-8a10-c8a546ad1807"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dfc7fee-f817-46ba-9106-57cb933d0881"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2dd4fbe-fad4-4295-bbbd-ba6899d66a83"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4e44fd2-c748-4cda-afdd-741229f2e981"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c9ec333-1da0-41c4-a1c2-5438757adeb4"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5334fe5-b6e4-4836-b06c-22cc50ae42ec"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hit9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""648cb1cb-812e-4083-b2a5-c13d073a20cd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa2a71c8-81bf-4522-a07c-2195bbad8072"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_hit1 = m_Game.FindAction("hit1", throwIfNotFound: true);
        m_Game_hit2 = m_Game.FindAction("hit2", throwIfNotFound: true);
        m_Game_hit3 = m_Game.FindAction("hit3", throwIfNotFound: true);
        m_Game_hit4 = m_Game.FindAction("hit4", throwIfNotFound: true);
        m_Game_hit5 = m_Game.FindAction("hit5", throwIfNotFound: true);
        m_Game_hit6 = m_Game.FindAction("hit6", throwIfNotFound: true);
        m_Game_hit7 = m_Game.FindAction("hit7", throwIfNotFound: true);
        m_Game_hit8 = m_Game.FindAction("hit8", throwIfNotFound: true);
        m_Game_hit9 = m_Game.FindAction("hit9", throwIfNotFound: true);
        m_Game_pause = m_Game.FindAction("pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_hit1;
    private readonly InputAction m_Game_hit2;
    private readonly InputAction m_Game_hit3;
    private readonly InputAction m_Game_hit4;
    private readonly InputAction m_Game_hit5;
    private readonly InputAction m_Game_hit6;
    private readonly InputAction m_Game_hit7;
    private readonly InputAction m_Game_hit8;
    private readonly InputAction m_Game_hit9;
    private readonly InputAction m_Game_pause;
    public struct GameActions
    {
        private @Controls m_Wrapper;
        public GameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @hit1 => m_Wrapper.m_Game_hit1;
        public InputAction @hit2 => m_Wrapper.m_Game_hit2;
        public InputAction @hit3 => m_Wrapper.m_Game_hit3;
        public InputAction @hit4 => m_Wrapper.m_Game_hit4;
        public InputAction @hit5 => m_Wrapper.m_Game_hit5;
        public InputAction @hit6 => m_Wrapper.m_Game_hit6;
        public InputAction @hit7 => m_Wrapper.m_Game_hit7;
        public InputAction @hit8 => m_Wrapper.m_Game_hit8;
        public InputAction @hit9 => m_Wrapper.m_Game_hit9;
        public InputAction @pause => m_Wrapper.m_Game_pause;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @hit1.started += instance.OnHit1;
            @hit1.performed += instance.OnHit1;
            @hit1.canceled += instance.OnHit1;
            @hit2.started += instance.OnHit2;
            @hit2.performed += instance.OnHit2;
            @hit2.canceled += instance.OnHit2;
            @hit3.started += instance.OnHit3;
            @hit3.performed += instance.OnHit3;
            @hit3.canceled += instance.OnHit3;
            @hit4.started += instance.OnHit4;
            @hit4.performed += instance.OnHit4;
            @hit4.canceled += instance.OnHit4;
            @hit5.started += instance.OnHit5;
            @hit5.performed += instance.OnHit5;
            @hit5.canceled += instance.OnHit5;
            @hit6.started += instance.OnHit6;
            @hit6.performed += instance.OnHit6;
            @hit6.canceled += instance.OnHit6;
            @hit7.started += instance.OnHit7;
            @hit7.performed += instance.OnHit7;
            @hit7.canceled += instance.OnHit7;
            @hit8.started += instance.OnHit8;
            @hit8.performed += instance.OnHit8;
            @hit8.canceled += instance.OnHit8;
            @hit9.started += instance.OnHit9;
            @hit9.performed += instance.OnHit9;
            @hit9.canceled += instance.OnHit9;
            @pause.started += instance.OnPause;
            @pause.performed += instance.OnPause;
            @pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @hit1.started -= instance.OnHit1;
            @hit1.performed -= instance.OnHit1;
            @hit1.canceled -= instance.OnHit1;
            @hit2.started -= instance.OnHit2;
            @hit2.performed -= instance.OnHit2;
            @hit2.canceled -= instance.OnHit2;
            @hit3.started -= instance.OnHit3;
            @hit3.performed -= instance.OnHit3;
            @hit3.canceled -= instance.OnHit3;
            @hit4.started -= instance.OnHit4;
            @hit4.performed -= instance.OnHit4;
            @hit4.canceled -= instance.OnHit4;
            @hit5.started -= instance.OnHit5;
            @hit5.performed -= instance.OnHit5;
            @hit5.canceled -= instance.OnHit5;
            @hit6.started -= instance.OnHit6;
            @hit6.performed -= instance.OnHit6;
            @hit6.canceled -= instance.OnHit6;
            @hit7.started -= instance.OnHit7;
            @hit7.performed -= instance.OnHit7;
            @hit7.canceled -= instance.OnHit7;
            @hit8.started -= instance.OnHit8;
            @hit8.performed -= instance.OnHit8;
            @hit8.canceled -= instance.OnHit8;
            @hit9.started -= instance.OnHit9;
            @hit9.performed -= instance.OnHit9;
            @hit9.canceled -= instance.OnHit9;
            @pause.started -= instance.OnPause;
            @pause.performed -= instance.OnPause;
            @pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);
    public interface IGameActions
    {
        void OnHit1(InputAction.CallbackContext context);
        void OnHit2(InputAction.CallbackContext context);
        void OnHit3(InputAction.CallbackContext context);
        void OnHit4(InputAction.CallbackContext context);
        void OnHit5(InputAction.CallbackContext context);
        void OnHit6(InputAction.CallbackContext context);
        void OnHit7(InputAction.CallbackContext context);
        void OnHit8(InputAction.CallbackContext context);
        void OnHit9(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
